--- #Testing the J2 Template Module
- hosts: webservers
  connection: ssh
  user: ubuntu
  sudo: yes
  gather_facts: yes
  vars:
    userName: ubuntu
    userPassword: password123
    connectionType: SFTP
  tasks:
    - name: Install the configuration file  customized for the system
      template: src=test.conf.j2 dest=/home/ubuntu/test.conf owner=ubuntu group=ubuntu mode=750
