--- #ERROR HANDLING EXAMPLE
- hosts: webservers
  user: ubuntu
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Execute a command that will faile
      command: /bin/false
      ignore_errors: yes
    - name: Install Telnet
      apt: pkg=telnet state=latest
    
