---
- hosts: webservers
  user: ubuntu
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install the telnet and lynx packages
      apt: pkg={{ item }} state=latest
      with_items:
        - telnet
        - lynx
      tags:
        - packages
    - name: verify that telnet was installed
      raw: apt list --installed | grep telnet > /home/ubuntu/telnet.log
      tags:
        - verification 
