--- # my first yaml playbook for ansible
- hosts: webservers
  user: ubuntu
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1l
  vars_files:
    - conf/cp.yml
  vars_prompt:
     - name: web_domain
       prompt: Web Domain
  tasks:
     - name: Install vsftpd
       action: apt name=vsftpd state=installed
     - name: Install telnet
       action: apt name=apache2 state=absent
